version: '3'
services:
  client:
    build: 
      context: ./client
      dockerfile: dockerfile
    ports: 
     - "3000:80"
    depends_on:
      - server

  server:
    build: 
      context: ./server
      dockerfile: Dockerfile
    ports: 
     - "4000:4000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/mydatabase
    depends_on:
      - mongo


  mongo: 
   image: mongo:latest
   ports:
     - "27017:27017"
   volumes: 
     - mongo_data:/data/db

volumes:
  mongo-data:
    driver: local